import { useState } from 'react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Switch } from '@/components/ui/switch';
import { Badge } from '@/components/ui/badge';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Brain, AlertTriangle, CheckCircle, XCircle } from 'lucide-react';
import { AICouncilResponse } from '@/types/medical';

interface DoctorAIPanelProps {
  aiInsights?: AICouncilResponse;
  onToggleAI: (enabled: boolean) => void;
  onAcceptInsight: (insight: string) => void;
  onRejectInsight: (insight: string) => void;
}

export function DoctorAIPanel({ aiInsights, onToggleAI, onAcceptInsight, onRejectInsight }: DoctorAIPanelProps) {
  const [aiEnabled, setAiEnabled] = useState(false);

  const handleToggle = (enabled: boolean) => {
    setAiEnabled(enabled);
    onToggleAI(enabled);
  };

  return (
    <Card className="border-blue-200">
      <CardHeader>
        <div className="flex items-center justify-between">
          <CardTitle className="flex items-center gap-2">
            <Brain className="h-5 w-5 text-blue-600" />
            AI Clinical Support
          </CardTitle>
          <Switch
            checked={aiEnabled}
            onCheckedChange={handleToggle}
            aria-label="Toggle AI insights"
          />
        </div>
      </CardHeader>
      
      {aiEnabled && aiInsights && (
        <CardContent className="space-y-4">
          <Alert>
            <AlertTriangle className="h-4 w-4" />
            <AlertDescription className="font-medium">
              {aiInsights.medical_disclaimer}
            </AlertDescription>
          </Alert>

          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-sm font-medium">Confidence Score</span>
              <Badge variant="secondary">
                {(aiInsights.confidence_score * 100).toFixed(0)}%
              </Badge>
            </div>

            <div>
              <h4 className="font-medium mb-2">Clinical Insights</h4>
              <div className="space-y-2">
                {aiInsights.insights.map((insight, index) => (
                  <div key={index} className="flex items-center justify-between p-2 bg-gray-50 rounded">
                    <span className="text-sm">{insight}</span>
                    <div className="flex gap-1">
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => onAcceptInsight(insight)}
                      >
                        <CheckCircle className="h-4 w-4 text-green-600" />
                      </Button>
                      <Button
                        size="sm"
                        variant="ghost"
                        onClick={() => onRejectInsight(insight)}
                      >
                        <XCircle className="h-4 w-4 text-red-600" />
                      </Button>
                    </div>
                  </div>
                ))}
              </div>
            </div>

            {aiInsights.risk_flags.length > 0 && (
              <div>
                <h4 className="font-medium mb-2 text-red-600">Risk Flags</h4>
                <div className="space-y-1">
                  {aiInsights.risk_flags.map((flag, index) => (
                    <Badge key={index} variant="destructive" className="mr-2">
                      {flag}
                    </Badge>
                  ))}
                </div>
              </div>
            )}

            <div className="text-xs text-gray-500 pt-2 border-t">
              Generated by: {aiInsights.generated_by} | Model: {aiInsights.model_version}
            </div>
          </div>
        </CardContent>
      )}
    </Card>
  );
}